### ISSUE TITLE
License(s)?

### ISSUE THREAD

**Issue by ptrandem** [ridomin/iothub-webclient#15]
Hi! I noticed this repo doesn't have a LICENSE file.
Under which license(s) is this offered (if any)?

**Comment by ridomin** [comment]
I created this project to learn how connect to IoT Hub using MQTT. Happy if this helps to anyone.

https://github.com/ridomin/iothub-webclient/commit/96a3a54c84c022fa0fc16e0a6f5651984272f474 adds a MIT License

Thanks !!
Rido

**Comment by ptrandem** [comment]
We have found this very helpful. Thank you for the license addition!
